package webbingocaller

object CallOuts {

  val callouts = Map(
    1 -> "Kelly’s eye, number 1",
    2 -> "One little duck, number 2",
    3 -> "Cup of tea, number 3",
    4 -> "Knock at the door, number 4",
    5 -> "Man alive, number 5",
    6 -> "Half a dozen, number 6",
    7 -> "Lucky for some, number 7",
    8 -> "Garden gate, number 8",
    9 -> "Doctor's orders, number 9",
    10 -> "Boris’s den, number 10",
    11 -> "Legs eleven, number 11",
    12 -> "One dozen, number 12",
    13 -> "Unlucky for some, number 13",
    14 -> "Valentine's Day, number 14",
    15 -> "Young and keen, number 15",
    16 -> "Sweet 16, number 16",
    17 -> "Dancing Queen, number 17",
    18 -> "Coming of age, number 18",
    19 -> "Goodbye teens, number 19",
    20 -> "One score, number 20",
    21 -> "Royal salute, number 21",
    22 -> "Two little ducks, number 22",
    23 -> "The Lord is My Shepherd, number 23",
    24 -> "Two dozen, number 24",
    25 -> "Duck and dive, number 25",
    26 -> "Pick and mix, number 26",
    27 -> "Gateway to Heaven, number 27",
    28 -> "Overweight, number 28",
    29 -> "Rise and shine, number 29",
    30 -> "Dirty Gertie, number 30",
    31 -> "Get up and run, number 31",
    32 -> "Buckle my shoe, number 32",
    33 -> "Dirty knee, number 33",
    34 -> "Ask for more, number 34",
    35 -> "Jump and jive, number 35",
    36 -> "Three dozen, number 36",
    37 -> "More than 11, number 37",
    38 -> "Christmas cake, number 38",
    39 -> "Steps, number 39",
    40 -> "Life begins, number 40",
    41 -> "Time for fun, number 41",
    42 -> "Winnie the Pooh, number 42",
    43 -> "Down on your knees, number 43",
    44 -> "Droopy drawers, number 44",
    45 -> "Halfway there, number 45",
    46 -> "Up to tricks, number 46",
    47 -> "Four and seven, number 47",
    48 -> "Four dozen, number 48",
    49 -> "PC, number 49",
    50 -> "It's a bullseye, number 50",
    51 -> "Tweak of the thumb, number 51",
    52 -> "Chicken vindaloo, number 52",
    53 -> "Here comes Herbie, number 53",
    54 -> "Man at the door, number 54",
    55 -> "All the fives, number 55",
    56 -> "Was she worth it, number 56",
    57 -> "Heinz varieties, number 57",
    58 -> "Make them wait, number 58",
    59 -> "Brighton line, number 59",
    60 -> "Five dozen, number 60",
    61 -> "Bakers bun, number 61",
    62 -> "Tickety-boo, number 62",
    63 -> "Tickle me, number 63",
    64 -> "Almost retired, number 64",
    65 -> "Old age pension, number 65",
    66 -> "Clickety click, number 66",
    67 -> "Stairway to Heaven, number 67",
    68 -> "Pick a mate, number 68",
    69 -> "Either way up, number 69",
    70 -> "Three score and 10, number 70",
    71 -> "Bang on the drum, number 71",
    72 -> "Six dozen, number 72",
    73 -> "Queen bee, number 73",
    74 -> "Candy store, number 74",
    75 -> "Strive and strive, number 75",
    76 -> "Trombones, number 76",
    77 -> "Two little crutches, number 77",
    78 -> "Heaven's gate, number 78",
    79 -> "One more time, number 79",
    80 -> "Gandhi's breakfast, number 80",
    81 -> "Fat lady with a walking stick, number 81",
    82 -> "Straight on through, number 82",
    83 -> "Time for tea, number 83",
    84 -> "Give me more, number 84",
    85 -> "Staying alive, number 85",
    86 -> "Between the sticks, number 86",
    87 -> "Torquay in Devon, number 87",
    88 -> "Two fat ladies, number 88",
    89 -> "Almost there, number 89",
    90 -> "Top of the shop, number 90"
  )

}
